---
functional:
  - пользователь должен иметь возможность искать товары по ключевому слову или категории
  - пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и так далее
  - пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен иметь мобильную версию
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика
  - сайт должен быть доступен на различных устройствах
  - у сайта должна быть адаптивная вёрстка
  - сайт должен быть SPA приложением, которое не перезагружает страницу
implicit:
  - у товаров должен быть постраничный вывод
  - пользователь может оформить заказ с переходом на страницу оплаты
  - корзина должна храниться в сессии браузера
  - цена товара меняется на рубли при изменении языка сайта на русский
  - знак доллара стоит перед числовым значением цены, если выбран английский язык сайта
